version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - .env

  frontend:
    image: okazivaetsya/foodgram_frontend:latest
    restart: always
    volumes:
      - frontend_value:/app/result_build/build/

  backend:
    image: okazivaetsya/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - frontend
    env_file:
      - .env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/
      
      - front_value:/usr/share/nginx/html/
      - static_rest:/usr/share/nginx/html/static/rest_framework/
      - static_admin:/usr/share/nginx/html/static/admin/
      - media_value:/usr/share/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  frontend_value:
  db_value:
