# Generated by Django 2.2.19 on 2022-11-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221122_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'ordering': ('ingredient',)},
        ),
    ]
