# Generated by Django 3.2.15 on 2022-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(max_length=30, verbose_name='Единица измерения'),
        ),
    ]
