# Generated by Django 3.2.15 on 2022-12-05 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsinrecipes',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'minimal quantity - 1')]),
            preserve_default=False,
        ),
    ]
