# Generated by Django 3.2.15 on 2022-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientsinrecipes_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsinrecipes',
            options={'ordering': ('recipe',), 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
        migrations.AddConstraint(
            model_name='ingredientsinrecipes',
            constraint=models.UniqueConstraint(fields=('ingredient', 'recipe'), name='unique_ingredients_in_recipe'),
        ),
    ]
