# Generated by Django 2.2.19 on 2022-12-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsamount',
            options={'ordering': ('ingredient',), 'verbose_name': 'Ингредиенты в рецептах', 'verbose_name_plural': 'Ингредиенты в рецептах'},
        ),
    ]
