# Generated by Django 2.2.19 on 2022-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=245, unique=True, verbose_name='Уникальное имя'),
        ),
    ]
